### ISSUE TITLE
Typo: No connection dialogue says "Not connection to server"

### ISSUE THREAD

**Issue by SEWsam** [RoganDawes/P4wnP1_aloa#133]
Typo. Dialogue shown when connection to server is lost says "Not connection to server" instead of "No connection to server".

**Comment by BohdanOpyr** [comment]
Also, HIDScript job details says "Sate", not "State"

**Comment by 21weberer** [comment]
Be glad you have a working image which can literally control computers from remote areas.

**Comment by SEWsam** [comment]
> Be glad you have a working image which can literally control computers from remote areas.

So....? This forum is for issues. Who cares if this issue doesn't affect the usage of the program, I'm reporting an issue whether it is important or not. Also, there is a perfectly working image on the releases page, so not like I'm lucky.

**Comment by 21weberer** [comment]
i know that. im saying that you should be glad that he did all of the installation and pre-configuration for you. perhaps i was a little harsh though, so my apologies.
