### ISSUE TITLE
Allow additional wpa_supplicant.conf in client mode

### ISSUE THREAD

**Issue by mame82** [RoganDawes/P4wnP1_aloa#20]
Allow providing a wpa_supplicant.conf file in WiFi client (station) mode, to attempt to connect to multiple known access points.

It has to be tested if this could still be combined with failover mode. Otherwise usage will be restricted to client mode

**Comment by SymbianSyMoh** [comment]
Any updates on this one? I was about to open a feature request to add the capability to the Client Mode to search and connect to more than one defined APs!
