### ISSUE TITLE
USB on PC

### ISSUE THREAD

**Issue by ChopsKingsland** [RoganDawes/P4wnP1_aloa#215]
After a successful install, I plug it into my pc, and it doesn't even show up! how can i fix this?

**Comment by PineMaster** [comment]
You have to look into the available wifis ......

**Comment by ChopsKingsland** [comment]
ive connected to the wifi on my phone, and im trying to run an HID script. It says it ran successfully, but nothing happens, and it doesnt show up on my pc.

**Comment by PineMaster** [comment]
did u use the data ports?
and check the script, if you are running Hidtest.1 then you have to place the cursor on ur pc somewhere

**Comment by PineMaster** [comment]
try saving this script https://pastebin.com/zjst6Af3 and running it, its a very basic script that opens notepad and types that ur p4wnp1 is working :]
Happy pwn'ng!

**Comment by ChopsKingsland** [comment]
it just says its running but nothing is happening, could it be a probelm with my pc?

**Comment by ChopsKingsland** [comment]
it cant be my pc, because it doesnt work on my laptop either. what are the correct settings for hid?

**Comment by PineMaster** [comment]
did you follow the vid i gave you in ur earlier issue, follow that first and test the script i gave you

**Comment by ChopsKingsland** [comment]
i followed the video a few months ago and it still didnt work. i followed it again and it still doesnt work

**Comment by PineMaster** [comment]
which script u testing?

**Comment by ChopsKingsland** [comment]
the one you sent

**Comment by ChopsKingsland** [comment]
i tried re-imaging the card and that hasnt sorted it either

**Comment by PineMaster** [comment]
did you disable mouse and enable mass storage (create disk from genimg)?

**Comment by ChopsKingsland** [comment]
yep i followed the whole tutorial and that didn't work ＞﹏＜

**Comment by ChopsKingsland** [comment]
@RoganDawes any ideas how to get it working?

**Comment by RoganDawes** [comment]
Let’s start at the beginning:
Disable all of the USB interfaces on the P4wnP1, then enable the keyboard and mouse, and SAVE that as the startup profile.
Reboot the Pi (or else apply the configuration), and check if you can see the keyboard/mouse on your target.

**Comment by ChopsKingsland** [comment]
ive done that and it doesnt work

the 'job' just stays at RUNNING
![image](https://user-images.githubusercontent.com/18499854/74763440-bafdc300-5277-11ea-924b-7bb62ede0215.png)

**Comment by RoganDawes** [comment]
Please can you verify that the cable is in fact capable of transferring data, and does not merely have the two power conductors of a "charge-only" cable? Depending on your OS, you could also check to see if the P4wnP1 HID devices are actually seen by the host. On Linux, you can run `dmesg -w` to see the messages as it is enumerated (run `dmesg -w` first, then plug the P4wnP1 in and wait for it to boot). On Windows you can check with the Device Manager to see what USB devices have been recognized, or you can use USBDeView (https://www.nirsoft.net/utils/usb_devices_view.html).

If nothing shows up, there are two possibilities: Either P4wnP1 is not properly creating the USB devices, or else the cable is the problem. Try with a different cable (or several different ones if you still have problems). Check with a phone or similar device if that is recognized by the Host OS when using that cable. Etc

**Comment by ChopsKingsland** [comment]
i have tried multiple cables, and that has not helped. it doesnt show up in device manager either...

**Comment by evilbobbins** [comment]
Are you plugging in the data usb to the pc or just the power one?

**Comment by PineMaster** [comment]
Yeah seems like a hardware problem to me :p

**Comment by ChopsKingsland** [comment]
ive tried using a new sd card with just raspian on, and the USB data port doesnt detect a keyboard or mouse. it still accepts power though...

**Comment by RoganDawes** [comment]
Attach a picture of your setup (cables, etc) so we can get a better idea.

**Comment by ChopsKingsland** [comment]
![EE6D5B9D-4E3D-4732-AAAB-D11D1A036CC4](https://user-images.githubusercontent.com/18499854/74832801-0499ec80-5310-11ea-9e6e-d309e62db364.jpeg)
I just plug this into USB. I’ve also tried it on my laptop and it doesn’t work. I have also tried with numerous cables too

**Comment by RoganDawes** [comment]
Ok. At least you are using the right port. I haven't played with the latest Raspbian, but as far as I recall, there is no default USB device configuration, so expecting to see one was misplaced.
If you have verified that the cable is working as a data cable with some other device, then I'm afraid I am out of ideas.

**Comment by PineMaster** [comment]
Other tha that it could only be the pi thats not able to send over data if you followed all of these comments and the vid, sorry i couldnt help

**Comment by Maow0** [comment]
I had the exact same issue tried a bunch of cables that didnt work, had to order a cable from amazon specifically with data lines. Problem solved! maybe you just got real unlucky with your cables check to see if when you plug in your phone etc with those same cables that they defo get picked up on your host OS's device manager.
