### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Dontkickmyscotch** [RoganDawes/P4wnP1_aloa#219]
Hi guys,

When i ssh pi@172.24.0.1 i tried "MaMe82-P4wnP1" as password but it tell s me permmision denied .

I dont get it, i tried all from the beggining a lot of times event i tried to change the password in the conf but still not working.

Any ideas?

**Comment by bohemianabe** [comment]
I see you closed this... i've tried 'toor', 'raspberry', and 'MaMe82-P4wnP1' without success. Help?

**Comment by whackyhack** [comment]
Default user for KALI Linux is _root_, not pi.
