### ISSUE TITLE
Settings reset after refreshing

### ISSUE THREAD

**Issue by doge-co** [RoganDawes/P4wnP1_aloa#260]
Hi,

After I store my settings and refresh the page they are reset to factory settings why is this?

**Comment by V0r-T3x** [comment]
Its normal if you refresh the page all your stored settings will be reset. You have to deploy your new settings to active it.

**Comment by doge-co** [comment]
It still happens after I deploy the settings, I get this error message too: Error while deploying new USB gadget settings
rpc error: code = Unknown desc = Response closed without headers.

**Comment by V0r-T3x** [comment]
What do you try to deploy? I already had one error like this when I tried to deploy a keyboard, a mouse AND a mass storage. If I try just the keyboard and mouse, this work. If I try just keyboard and mass storage, this work too. But three of them don't work.

**Comment by doge-co** [comment]
I just tried deploying then saving the settings and it worked.

**Comment by doge-co** [comment]
It was keyboard and mass storage.
