### ISSUE TITLE
Run on other linux distro

### ISSUE THREAD

**Issue by Jacob-Marshall** [RoganDawes/P4wnP1_aloa#283]
Hi,

I'd like to run p4wnp1 on an os other to kali. Is this possible or should I revert to the old repo?

Thanks,
Jacob

**Comment by whackyhack** [comment]
P4wnP1_aloa is a completely new project that is built on Kali.

**Comment by Jacob-Marshall** [comment]
Ok thanks, so it only works on kali?

**Comment by TheMMcOfficial** [comment]
I don't know why you want to run PwnP1 on an other distro. Why you should use kali: the tools but the most important the wireless driver to be able to make an acess point with your raspberry pi zero. It may have other requirements...

**Comment by Jacob-Marshall** [comment]
Ok thanks for your help
