### ISSUE TITLE
The PI ZERO cannot boot again.

### ISSUE THREAD

**Issue by SeanChangX** [RoganDawes/P4wnP1_aloa#298]
Just use it a few times, and the PI ZERO cannot boot again. The onboard green LED always lights up(It won't blink). If I flash the firmware again, it can work again.

**Comment by gloglas** [comment]
Try debugging it. Hook up a hdmi monitor to it or via serial interface.

**Comment by Brodontcode** [comment]
I am also having the same problem can anybody help?
