### ISSUE TITLE
How to keep P4wnP1 trying to connect to WiFi

### ISSUE THREAD

**Issue by LegendL3n** [RoganDawes/P4wnP1_aloa#301]
Hi there, I'd like to know if it's possible, with the current options, to let P4wnP1 keep trying to connect to WiFi if it didn't/isn't succeeding.

I tried messing with the options but haven't achieved anything, I wonder if there's something simple I hadn't thought of.

Thanks in advance :).

**Comment by gloglas** [comment]
I don't think that there is such a feature. But you could edit the go code or you can simply write bash script for it.
