### ISSUE TITLE
Website (not an issue just a question)

### ISSUE THREAD

**Issue by Programmer1603** [RoganDawes/P4wnP1_aloa#311]
Is it possible to host the webserver in the public worldwideweb? 
So u can plug it in and acess it later on at any given time?
With nginx for example?

Thank you in advance

**Comment by V0r-T3x** [comment]
@Programmer1603  if you have a port forward on your router you can already access it from everywhere. If you dont have right to configure the router it can be more tricky to access it. I cant show you how to achieve this. To control it from anywhere, I use a reverse SSH tunnel. I hope this can help you.

**Comment by Programmer1603** [comment]
Ty
