### ISSUE TITLE
I want to provide the location of the module's web page file

### ISSUE THREAD

**Issue by LuckyFishGeek** [RoganDawes/P4wnP1_aloa#45]
I want to translate into Chinese  and I also want permission from the author.

**Comment by mame82** [comment]
Permission wise this shouldn't be a problem (GPLv3), but I haven't externalized  the strings used by the webclient to a central file.

As all strings are embedded in the webclients Go sources, I suggest to open a dedicated fork.

**Comment by CN-P5** [comment]
> I want to translate into Chinese and I also want permission from the author.

有计划了吗？
